name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t flask-cicd-app .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag flask-cicd-app ${{ secrets.DOCKER_USERNAME }}/flask-cicd-app:latest

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-cicd-app:latest